### ISSUE TITLE
npm pkg / unsupported_platform error

### ISSUE THREAD

**Issue by Palletus** [johnvmt/node-desktop-screenshot#13]
Not sure if this is more pkg or desktop-screenshot related problem, but let's give a try here. When I compile my js to exe with pkg, I always get "unsupported_platform" error when taking screenshot. This has been only tested in Win10 enviroment.  When running js with node, everything works fine. I've tried to compile x86/x64 with node 8 / latest targets but always same error. Does anyone have any idea whats happening here? Thanks!

**Comment by Palletus** [comment]
Resolved issue by placing nircmd.exe other location and modify path to win32.js.

**Comment by spitrola** [comment]
May I have more clarification on how you resolved the issue? As I am having the same issue.

**Comment by Palletus** [comment]
Modify node_modules/desktop-screenshot/capture/win32.js nircmd variable path to whatever you like and place nircmd executable to that folder outside your program. As far as I know, you can't embed that nircmd.exe with pkg.
